org: devopmh
app: grocery-store
service: grocery-store

package:
  individually: true
build:
  esbuild:
    minify: true

plugins:
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs20.x
  logRetentionInDays: 7
  versionFunctions: false
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
            - 'dynamodb:Query'
            - 'dynamodb:DescribeTable'
          Resource:
            - 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${sls:stageParams.tableName}'
            - 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${sls:stageParams.tableName}/index/*'
  environment:
    TABLE_NAME: ${self:service}-${sls:stage}

resources:
  Resources:
   DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: '${sls:stageParams.tableName}'
      BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: 'pk'
        AttributeType: 'S'
      - AttributeName: 'sk'
        AttributeType: 'S'
      - AttributeName: 'pkBrandPrice'
        AttributeType: 'S'
      - AttributeName: 'skBrandPrice'
        AttributeType: 'S'
      - AttributeName: 'pkCategoryBrandPrice'
        AttributeType: 'S'
      - AttributeName: 'skCategoryBrandPrice'
        AttributeType: 'S'
      - AttributeName: 'pkProduct'
        AttributeType: 'S'
      - AttributeName: 'stock'
        AttributeType: 'N'
      - AttributeName: 'price'
        AttributeType: 'N'

    KeySchema:
      - AttributeName: 'pk'
        KeyType: 'HASH'
      - AttributeName: 'sk'
        KeyType: 'RANGE'

    GlobalSecondaryIndexes:
      - IndexName: 'brandPriceIndex'
        KeySchema:
          - AttributeName: 'pkBrandPrice'
            KeyType: 'HASH'
          - AttributeName: 'skBrandPrice'
            KeyType: 'RANGE'
        Projection:
          ProjectionType: 'INCLUDE'
          NonKeyAttributes:
            - 'price'
      - IndexName: 'categoryBrandPriceIndex'
        KeySchema:
          - AttributeName: 'pkCategoryBrandPrice'
            KeyType: 'HASH'
          - AttributeName: 'skCategoryBrandPrice'
            KeyType: 'RANGE'
        Projection:
          ProjectionType: 'ALL'
      - IndexName: 'productIndex'
        KeySchema:
          - AttributeName: 'pkProduct'
            KeyType: 'HASH'
        Projection:
          ProjectionType: 'INCLUDE'
          NonKeyAttributes:
            - 'stock'
      - IndexName: 'categoryPriceIndex'
        KeySchema:
          - AttributeName: 'pkCategoryPrice'
            KeyType: 'HASH'
          - AttributeName: 'price'
            KeyType: 'RANGE'
        Projection:
          ProjectionType: 'ALL'
functions:
  create:
    handler: src/functions/products/create/index.handler
    events:
      - httpApi:
          path: /products/create
          method: post
    environment:
      TABLE_NAME: ${sls:stageParams.tableName}
  get:
    handler: src/functions/products/get/index.handler
    events:
      - httpApi:
          path: /products/get
          method: get
    environment:
      TABLE_NAME: ${sls:stageParams.tableName}
  getOne:
    handler: src/functions/products/get-one/index.handler
    events:
      - httpApi:
          path: /products/get/{id}
          method: get
    environment:
      TABLE_NAME: ${sls:stageParams.tableName}
  update:
    handler: src/functions/products/update/index.handler
    events:
      - httpApi:
          path: /products/update
          method: put
    environment:
      TABLE_NAME: ${sls:stageParams.tableName}
  delete:
    handler: src/functions/products/delete/index.handler
    events:
      - httpApi:
          path: /products/delete
          method: delete
    environment:
      TABLE_NAME: ${sls:stageParams.tableName}

