name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - dev*

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ job.environment }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy with serverless to ${{ job.environment }}
        if: success() && ${{ job.environment }}
        run: npx serverless deploy --stage ${{ job.environment }}
        env:
          NODE_ENV: ${{ job.environment }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
